### ISSUE TITLE
Jetty JAASLoginService should not use getContextClassLoader to load role class name under OSGi

### ISSUE THREAD

**Issue by jmcc0nn3ll** [eclipse/jetty.project#110]
migrated from Bugzilla [#403119](https://bugs.eclipse.org/bugs/show_bug.cgi?id=403119)
status ASSIGNED severity _enhancement_ in component _server_ for _9.0.x_
Reported in version _7.4.5_ on platform _All_
Assigned to: Jan Bartel

Original attachment names and IDs:
- _[jaas_role_osgi.diff](https://bugs.eclipse.org/bugs//attachment.cgi?id=228309)_ (ID 228309)

On 2013-03-12 16:26:05 -0400, metatech wrote:

> Created attachment 228309
> jaas_role_osgi
> 
> Jetty JAASLoginService.getGroups() contains some logic to filter JAAS role principals from JAAS user principals.
> For that purpose, it tries to load all "role class names" with the "context class loader", which unfortunately has different semantics under OSGi than in a regular Java EE application server.
> This can cause ClassNotFoundException when trying to load the class.
> 
> The proposed solution is to retrieve all principals from the subject and compare the type hierarchy of each object's class (+ all super-classes and their implemented interfaces) to the list of "role class names" configured in Jetty.
> This makes it OSGi-friendly.
> 
> Please see implementation in attachment.
> Tested under Jetty 7.4.5 within ServiceMix 4.4.2.
> 
> java.lang.RuntimeException: java.lang.ClassNotFoundException: org.apache.karaf.jaas.modules.RolePrincipal not found by mycomponent [204]
>   at org.eclipse.jetty.plus.jaas.JAASLoginService.getGroups(JAASLoginService.java:279)[58:org.eclipse.jetty.plus:7.4.5.v20110725]
>   at org.eclipse.jetty.plus.jaas.JAASLoginService.login(JAASLoginService.java:209)[58:org.eclipse.jetty.plus:7.4.5.v20110725]
> Caused by: java.lang.ClassNotFoundException: org.apache.karaf.jaas.modules.RolePrincipal not found by mycomponent [204]
>   at org.apache.felix.framework.ModuleImpl.findClassOrResourceByDelegation(ModuleImpl.java:787)[org.apache.felix.framework-3.0.9.jar:]
>   at org.apache.felix.framework.ModuleImpl.access$400(ModuleImpl.java:71)[org.apache.felix.framework-3.0.9.jar:]
>   at org.apache.felix.framework.ModuleImpl$ModuleClassLoader.loadClass(ModuleImpl.java:1768)[org.apache.felix.framework-3.0.9.jar:]
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:247)[:1.6.0_35]
>   at org.eclipse.jetty.plus.jaas.JAASLoginService.getGroups(JAASLoginService.java:267)[58:org.eclipse.jetty.plus:7.4.5.v20110725]
>   ... 18 more
> 
> Thanks.

On 2013-03-27 19:42:51 -0400, Jan Bartel wrote:

> metatech,
> 
> Firstly, jetty-7.4.5 is really old now, and the impl of the OSGi infrastructure has changed significantly in jetty-8 and jetty-9. Could you please try your test app under at least the latest jetty-8 (but preferably 9) and report if the problem still exists?
> 
> If it does, can you provide a small project that demonstrates it please? I'd like to see the manifests of your bundles to understand how you're deploying jetty and your webapp and karaf. If karaf is external to your webapp bundle, then have you declared an import for those classes in the manifest of the bundle of your webapp??  I'm not denying that there could be an issue with the loading of role classes under OSGi, but I need to see a non-working example to be sure that if there is a problem, we fix it the right way. 
> 
> thanks
> Jan

On 2013-03-29 07:06:43 -0400, metatech wrote:

> Hi Jan,
> Thanks for your answer.
> I understand your request to have a stand-alone project which reproduces the problem.  Unfortunately, we did extensive customization the software stack we use (based on ServiceMix 4.4.2), so I think it will require significant time for me to produce it, which I do not have in the short term.
> A small enhancement that would help us override the default JAASLoginService without patching the Jetty JAR is to convert the method "getGroups" from "private" to "protected".
> When I have some time, I will try to create a test project.

**Comment by metatechbe** [comment]
Here is a simple way to reproduce it.
1. Download ServiceMix (for instance 5.4.x), install and start it.
2. Make sure that property "org.ops4j.pax.web.config.file=etc/jetty.xml" is defined in all files named etc/org.ops4j.pax.web.cfg.*
3. Download http://central.maven.org/maven2/org/ops4j/pax/web/samples/war-formauth/3.2.4/war-formauth-3.2.4.war and copy it in "deploy" directory of ServiceMix.
4. Access http://localhost:8181/war-formauth/wc/example, enter "smx" and "smx" as username/password in the form, and click "Login".

You get the following exception in the logs : 
Caused by: java.lang.ClassNotFoundException: org.apache.karaf.jaas.boot.principal.RolePrincipal not found by war-formauth [381]

**Comment by janbartel** [comment]
@metatechbe  I downloaded 6.1.3 and followed your steps. It seemed to work, no exceptions in the log and I see a Hello World page. Same for 7.0.0, it appears to work.

However, I downloaded 5.6.3 and it didn't work at all - nothing to do with jaas, but a jsp compilation issue for login.jsp instead.

Is this issue still a problem, or has it been resolved by servicemix/karaf?

**Comment by metatechbe** [comment]
Hello,
Thanks for looking into this.
I did the test again with ServiceMix 6.3.1, and indeed, it does work with this version.

After some experimenting, is is due to the change in Karaf, where the package "org.apache.karaf.jaas.boot.principal" was added in the "org.osgi.framework.bootdelegation" of file "etc/custom.properties".

Anyway, it is still not OSGi-friendly to load a class from the Thread Context ClassLoader (TCCL) in Jetty, because the TCCL is undefined in OSGi :

> Many java libraries exist that use the context class loader. In an OSGi Framework environment the context class loader is not defined. 

https://wiki.eclipse.org/Context_Class_Loader_Enhancements

This was the reason why I changed the classloading logic into a class hierarchy comparison logic.

metatech

**Comment by joakime** [comment]
This detail about the TCCL and OSGi seems like it could explain Issue #1448 as well

**Comment by metatechbe** [comment]
Beware that the TCCL is undefined by the OSGi specification, but in actual implementations, it will often be defined to a certain classloader (that means not "null"), depending on the container, and the various libraries deployed and used on the code path.  This allows some compatibility with libraries which still use discouraged class loading methods such as "Class.forName(...)".

**Comment by janbartel** [comment]
@metatechbe I've just had a quick read of http://felix.apache.org/documentation/subprojects/apache-felix-jaas.html.

It seems to me that jetty's JAASLoginService probably shouldn't be used in an OSGi environment:  it looks like the various OSGi containers have solved the fundamental JAAS/OSGi impedance mismatch problem in different ways and thus the best thing to do would be for each container to implement jetty's [LoginService](http://www.eclipse.org/jetty/javadoc/9.4.6.v20170531/org/eclipse/jetty/security/LoginService.html) interface as appropriate.  What do you think?

**Comment by janbartel** [comment]
Fix was applied.
