### ISSUE TITLE
 Network sockets not properly closed

### ISSUE THREAD

**Issue by ari** [eclipse/jetty.project#4418]
FreeBSD 12.1
java/openjdk11.0.5+10.1 from ports
jetty-9.4.24.v20191120 (although the problem certainly exists in 9.4.21 and probably other versions)

There appears to be a serious problem with Jetty 9.4 specific to openJDK11/12 on FreeBSD. The problem does not happen in openJDK13 nor does it happen with tomcat. It can be reproduced easily.

Inbound connections to a jetty server running HTTP/2 with either TLS 1.2 or 1.3 result in dropped connections randomly (about one in 100 at first). The connection remains in CLOSED state according to sockstat and is never released.

As the number of sockets builds up, more and more connections are dropped until the server stops responding entirely.

We've reproduced this in our own application and also noted it happening in Apache Solr 8.2.0.

Reverting to openjdk8 or upgrading to openjdk13 fixes the problem. Using -Djdk.net.usePlainSocketImpl with openjdk13 doesn't cause the problem to happen, so the work done in https://bugs.openjdk.java.net/browse/JDK-8218559 may not be relevant to this issue.

**Comment by ari** [comment]
Note that the lead porter of openJDK to FreeBSD can reproduce the problem but we could do with a hand to understand what is specific to Jetty's socket handling which might contribute to this issue.

https://github.com/battleblow/openjdk-jdk11u/issues/94

**Comment by ari** [comment]
@gregw We had some dealings with webtide years ago and we are based about 5km from you. Let me know if you need a FreeBSD environment to assist with testing, if you don't already have one.

**Comment by gregw** [comment]
@ari I'm guessing that this is more likely an openJDK bug than a jetty bug.... as I'm trying to think what could we possibly do to get a connection into CLOSED state and have it stay there and never be released.  I'm not sure I could write code to do that even if I wanted!

Can you capture a full debug trace from jetty while reproducing and we can have a look at it and annotate exactly what we are doing.
Even stranger that it is only HTTP/2... So the debug trace will be helpful to see why it is dropping the connection.

Is it possible for you to test with h2c (ie no SSL) to see if you can get the same problem without SSL?

**Comment by ari** [comment]
Here is a script to reproduce the problem and the debug logs in the output. Hopefully that's enough to give you some clues for where the problem is happening.

https://gist.github.com/angeloudy/fbc09619fd6c54544fd631b6f040cf1e

**Comment by ari** [comment]
Also inviting @battleblow to this ticket. He is the lead FreeBSD porter for openJDK and has reproduced the problem.

**Comment by ari** [comment]
Is there any more we can do to help? We'd love to know why Jetty isn't properly closing sockets on FreeBSD?

**Comment by joakime** [comment]
A replication would help.
Do you have a series of steps with perhaps the demo-base (from the jetty-distribution) that can replicate on a freebsd docker image?

**Comment by ari** [comment]
There is a script in https://gist.github.com/angeloudy/fbc09619fd6c54544fd631b6f040cf1e

**Comment by joakime** [comment]
Your example is incomplete and bad.

From your gist logs ...
```
java.lang.NoSuchMethodError: 'int javax.servlet.http.HttpServletResponse.getStatus()'
```

That says you are running an older version of the javax.servlet API then the server needs/supports.

## Test run 

If we run https://github.com/jetty-project/embedded-jetty-cookbook/blob/master/src/main/java/org/eclipse/jetty/cookbook/SimplestServer.java
And your curl script from your gist then nothing outstanding happens.


```
[embedded-jetty-cookbook][master]$ mvn --version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T13:41:47-05:00)
Maven home: /home/joakim/java/apache-maven-3.6.0
Java version: 11.0.6, vendor: AdoptOpenJDK, runtime: /home/joakim/java/jvm/jdk-11.0.6+10
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.3.0-7625-generic", arch: "amd64", family: "unix"

[embedded-jetty-cookbook][master]$ mvn clean install org.codehaus.mojo:exec-maven-plugin:1.6.0:java -Dexec.mainClass=org.eclipse.jetty.cookbook.SimplestServer
[INFO] Scanning for projects...
...(snip)...
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ embedded-jetty-cookbook ---
2020-02-10 08:27:50.062:INFO::org.eclipse.jetty.cookbook.SimplestServer.main(): Logging initialized @2986ms to org.eclipse.jetty.util.log.StdErrLog
2020-02-10 08:27:50.092:INFO:oejs.Server:org.eclipse.jetty.cookbook.SimplestServer.main(): jetty-9.4.26.v20200117; built: 2020-01-17T12:35:33.676Z; git: 7b38981d25d14afb4a12ff1f2596756144edf695; jvm 11.0.6+10
2020-02-10 08:27:50.102:DBUG:oejsh.AbstractHandler:org.eclipse.jetty.cookbook.SimplestServer.main(): starting Server@7032c52f{STARTING}[9.4.26.v20200117]
2020-02-10 08:27:50.107:DBUG:oejsh.AbstractHandler:org.eclipse.jetty.cookbook.SimplestServer.main(): starting ErrorHandler@4ef8bfe6{STARTING}
2020-02-10 08:27:50.133:INFO:oejs.AbstractConnector:org.eclipse.jetty.cookbook.SimplestServer.main(): Started ServerConnector@83de19{HTTP/1.1,[http/1.1]}{0.0.0.0:9090}
2020-02-10 08:27:50.134:INFO:oejs.Server:org.eclipse.jetty.cookbook.SimplestServer.main(): Started @3058ms
Hint: Hit Ctrl+C to stop Jetty.
```

Any different terminal for curl ...

```
$ curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
$ for i in {1..20000}; do for j in {1..20}; do curl http://localhost:9090/&  done;wait; done
...(snip)...
$ netstat -tn | grep 9090 | wc -l
14079
```

All of the connections result in a 404 status response, and are kept open (per curl defaults).
The netstat shows a mess of TIME_WAIT connections.
This is normal and expected behavior for TCP and how you are using curl.
Notice the messages ....

```
Connection #0 to host localhost:9090 left intact
```

Now lets wait 2 minutes ...

```
$ netstat -tn | grep 9090 | wc -l
0
```

All cleaned up, via normal TCP stack behaviors for how those connections were used.

**Comment by joakime** [comment]
Now lets see what happens when we use a load testing tool that was written properly, and not abusing curl.

```
$ ab -n 20000 -c 20 http://localhost:9090/
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 2000 requests
Completed 4000 requests
Completed 6000 requests
Completed 8000 requests
Completed 10000 requests
Completed 12000 requests
Completed 14000 requests
Completed 16000 requests
Completed 18000 requests
Completed 20000 requests
Finished 20000 requests


Server Software:        Jetty(9.4.26.v20200117)
Server Hostname:        localhost
Server Port:            9090

Document Path:          /
Document Length:        437 bytes

Concurrency Level:      20
Time taken for tests:   1.052 seconds
Complete requests:      20000
Failed requests:        0
Non-2xx responses:      20000
Total transferred:      12220000 bytes
HTML transferred:       8740000 bytes
Requests per second:    19019.51 [#/sec] (mean)
Time per request:       1.052 [ms] (mean)
Time per request:       0.053 [ms] (mean, across all concurrent requests)
Transfer rate:          11348.55 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       1
Processing:     0    1   0.1      1       4
Waiting:        0    0   0.1      0       4
Total:          0    1   0.2      1       5

Percentage of the requests served within a certain time (ms)
  50%      1
  66%      1
  75%      1
  80%      1
  90%      1
  95%      1
  98%      1
  99%      2
 100%      5 (longest request)
$ netstat -tn | grep 9090 | wc -l
0
```

**Comment by ari** [comment]
The problem is real (it happens in production), so I'll try your approach to get another better set of logs for you. Thanks for your time.

**Comment by martinkovacik** [comment]
I can confirm the behavior described by @ari . My setup is slightly different however:
FreeBSD 11.3, 12.0, 12.1
openjdk11-11.0.5+10.1 from packages
jetty-9.4.24.v20191120

Inbound connections are non TLS HTTP/1.1 (TLS is terminated in NGINX in front of jetty).
Problem started after migrating from openjdk8 to opendjk11.

**Comment by sbordet** [comment]
@ari @martinkovacik can you confirm that you get the stack trace reported [here](https://github.com/battleblow/openjdk-jdk11u/issues/94#issuecomment-559669209)?

If that is the case, then I think it's a JDK bug, as they should catch the `IOException` and continue the iteration in `SelectorImpl.processDeregisterQueue()`.

Unfortunately, because the exception happens during the `select()` operation, the selector is now dead and Jetty won't (by default) throw it away and restart it and even if it does, a single socket failing in that way will cause all other sockets - that may function normally - to become "lost" in a dead selector.

See also #3989.

**Comment by sbordet** [comment]
Sent a message to OpenJDK's nio-dev: https://mail.openjdk.java.net/pipermail/nio-dev/2020-February/007051.html

**Comment by ari** [comment]
@sbordet Yes, angeloudy actually works in my team and I asked him to investigate the cause of the problems we had in production.

I think you are right that this is a JDK bug since the problem goes away in Java 13. Your clue about processDeregisterQueue leads us to:

* [Java11](https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/5f01925b80ed851b133ee26fbcb07026ac04149e/src/java.base/share/classes/sun/nio/ch/SelectorImpl.java#L267)
* [Java13](https://github.com/AdoptOpenJDK/openjdk-jdk13u/blob/bb0786d980437800b9d6efe17e42d18241714ea1/src/java.base/share/classes/sun/nio/ch/SelectorImpl.java#L189)

And [this commit](https://github.com/AdoptOpenJDK/openjdk-jdk13u/commit/6334117e77649249e13b72e135d97318039c5d71#diff-a7b6717ba777d7e6c02b0519a2f0f088) seems to suggest some locking issue was fixed in Java13.

**Comment by sbordet** [comment]
@ari, I think the locking issue is orthogonal to this problem, as the call to `kill()` can still throw and abort the iterator, and unwind to the outer `select()` call.

Basically Jetty does not like `select()` to fail at all - the only thing we can do is to close the selector, and we are not sure that is enough to close all socket channels either (and the selector can be in a state where the keys cannot be retrieved).

Would you or @battleblow be able to patch the FreeBSD port (wrapping the call to `kill()`) and produce a binary that you can try?

**Comment by martinkovacik** [comment]
@sbordet yes I can confirm I'm getting exactly the same stack trace as reported [here](https://github.com/battleblow/openjdk-jdk11u/issues/94#issuecomment-559669209).

**Comment by sbordet** [comment]
@ari @martinkovacik the follow up on the nio-dev mailing list indeed points to a JDK issue.

This has been fixed (via other fixes) in OpenJDK 13 for the Oracle supported platforms (FreeBSD is not one of them).

I don't know if the FreeBSD OpenJDK 13 port has similar fixes, but there is not much we can do from the Jetty side.

**Comment by ari** [comment]
Thanks for all your work on this, it has been very helpful. I'll close this task since it isn't Jetty although it is triggered more often by Jetty than anything else.

https://github.com/battleblow/openjdk-jdk11u/ is the canonical FreeBSD port. Its nice to see that Oracle will probably fix this in a JDK11 patch. Would it help to create a ticket somewhere to track that, or do they have their own process?

Again, thanks for all your help to track down the cause.

**Comment by sbordet** [comment]
@ari, I believe you will have more luck with @battleblow fixing the FreeBSD implementation to not throw, than Oracle doing a complicated backport to 11.
You can use https://bugreport.java.com/bugreport/ and point to the nio-dev discussion as well as this issue.
