### ISSUE TITLE
Jetty Documentation link is pointing to Archived Eclipse Projects

### ISSUE THREAD

**Issue by mikelee3** [eclipse/jetty.project#4841]
I've recently started using Jetty on an existing project and am trying to find the documentation.

The README.md says that the documentation for jetty is here
https://www.eclipse.org/jetty/documentation

However, it seems that everything under this url is redirecting here:
https://www.eclipse.org/projects/archives.php

Is this intentional? I cannot find anything about Jetty on the archives page and the links in the documentation on this github project are pointing to the page that gets redirected.

Could the documentation links be updated if they should go to another location?

Thanks

**Comment by sbordet** [comment]
@mikelee3 sorry about this, we are talking to Eclipse to restore the website, which is pointing to the archives by mistake.

Thanks for reporting this, we'll update the issue as soon as it is resolved.

**Comment by jmcc0nn3ll** [comment]
I believe this is an issue with a bad regex on the eclipse side, a project called JET was recently archived and I think that is catching all eclipse jetty website traffic and making it look like the project is archived.

The issue has been re-escalated and hopefully will be sorted out soon!

**Comment by sbordet** [comment]
The website has been restored.

Closing the issue, please post whether it works for you, or if you have further problems.

Thanks!

**Comment by mikelee3** [comment]
Thanks, it's working for me now!

**Comment by sirianni** [comment]
I still get redirected to the archive page.  Where can the documentation be found?

```
$ http https://www.eclipse.org/jetty/documentation   
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Content-Length: 162
Content-Security-Policy: frame-ancestors 'self'
Content-Type: text/html
Date: Mon, 20 Mar 2023 16:00:22 GMT
Location: https://www.eclipse.org/projects/archives.php
Server: nginx
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by jmcc0nn3ll** [comment]
Apparently, the Eclipse webmasters have their redirects mucked up again, I'll reach out to them.
