### ISSUE TITLE
Correct Usage of ServletContainerInitializer with @HandlesTypes

### ISSUE THREAD

**Issue by thuri** [eclipse/jetty.project#5051]
**Jetty version** 
9.4.30.v20200611
**Java version**
11
**Question**
I wanted to use Spring MVC in a project that already contains an embedded jetty server. And i hoped that I could simply add an WebApplicationInitializer implementation to my project to setup everything. I found some examples on the net and tried to add an WebAppContext to my handlers that gets an AnnotationConfiguration. But the WebApplicationInitializer is not called. 

So I started debugging the app and found out that the org.springframework.web.SpringServletContainerInitializer SPI is called by jetty but the passed parameter webAppInitializerClasses, that should contain my WebApplicationInitializerimplementation is not present. 

I thought it was an ClassLoaderIssue but then had a look at the callstack and saw that only the _applicableTypeNames Array is used to load classes and which was empty in my case. The needed interface WebApplicationInitializer was added only to the _interestedTypes array when the ContainerInitializer(ServletContainerInitializer, Class<?>[]) was called.

So i don't know where my error is or whether it may be a bug in jetty or Spring (5.2.6.RELEASE)

I created a minimal project to reproduce: https://github.com/thuri/SpringOnEmbeddedJetty
If you simply start the main class a server is created but the System.out.println that I'va added to the WebApplicationInitilizer implementation is not called

Any help would be appreciated. Thanks in advance

**Comment by thuri** [comment]
While writing the above question I had a deeper look at the org.eclipse.jetty.plus.annotation.ContainerInitializer.resolveClasses(WebAppContext, Map<String, Set<String>>) method.

The passed "classMap" is always empty and the caller (org.eclipse.jetty.annotations.AnnotationConfiguration) doesn't seem to fill it at all. 
So it seems I have to fill it myself like in this SO question/answer: https://stackoverflow.com/questions/11447104/embedded-jetty-8-x-spring-mvc-webapplicationinitializer

Is this the correct way to do this? Why can't jetty itself find the implementations of the Interface of the @HandleTypes Annotation on the ServletContainerInitializer?

**Comment by janbartel** [comment]
@thuri I think the minimal project is a bit too minimal to be useful: for example, you can't just set only the AnnotationConfiguration in the list of configurations to call :)

If you can report more about the setup of your webapp, then we can be more helpful. For example, what is the code that sets up embedded jetty? How did you add a WebAppContext? How did you enable the AnnotationConfiguration? Have you set the org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern at all? Are the spring jars on the server classpath or on the webapp classpath?

Have you seen the documentation here, which has embedded examples of working with annotations (not necessarily spring annotations, but the basic concept is the same): https://www.eclipse.org/jetty/documentation/9.4.30.v20200611/annotations.html

**Comment by thuri** [comment]
Hi and thanks for the fast response.

Yeah the example is minimal :-) But I used in only to see whether the WebApplicationInitializer implementation will be found by the Container and called. If it would then it should have been printed "This is not called" to the console.

But I did found a way now by adding implementations of WebApplicationInitializer to the container by specifying a ClassinheritanceMap to the AnnotationConfiguration.
See https://github.com/thuri/SpringOnEmbeddedJetty/commit/fdd031ae7486810030fcd73e4f4bc309830eecbb 
The class is now picked up and the method is called as wanted. I will now proceed to add more configuration 

Thanks for the documentation link. I'll have a look at it.

**Comment by janbartel** [comment]
@thuri you really shouldn't need to do anything with a ClassInheritanceMap: jetty is capable of discovering everything needed, provided it is given the correct configuration. Take a look at the doco, and I also recommend that you enable DEBUG level logging for org.eclipse.jetty.annotations package - that will show you which SCIs have been discovered or rejected etc.

**Comment by joakime** [comment]
@thuri this is all you need ...

``` java
package net.lueckonline.jetty;

import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.webapp.Configuration;
import org.eclipse.jetty.webapp.WebAppContext;

public class Application {

  private static final boolean webappIsolation = true;

  public static void main(String[] args) throws Exception {
    Server server = new Server();

    // Enable annotation scanning
    Configuration.ClassList classlist = Configuration.ClassList.setServerDefault(server);
    classlist.addBefore("org.eclipse.jetty.webapp.JettyWebXmlConfiguration",
        "org.eclipse.jetty.annotations.AnnotationConfiguration");

    WebAppContext webAppContext = new WebAppContext();
    webAppContext.setContextPath("/api");
    // Base Resource is required
    webAppContext.setResourceBase("src/main/base-resource");

    // There are 2 paths you can take here.

    if (webappIsolation) {
      // PATH 1:
      // This WebAppContext needs something in it's classloader, otherwise all of the
      // classes belong to the server.
      webAppContext.setExtraClasspath("target/classes");
    } else {
      // PATH 2:
      // Invert the classloader priority from Servlet based to Java based.
      webAppContext.setParentLoaderPriority(true);
    }

    server.setHandler(webAppContext);

    server.start();
    server.join();
  }
}
```

**Comment by joakime** [comment]
If you intend to make this a uber jar, with no external WebAppContext deployment, choose `webappIsolation = false`.

**Comment by thuri** [comment]
Thank you both very much.

So I need to use the ClassList and add the AnnotationConfiguration "before" the JettyWebXmlConfiguration because the later is always there? Why can't I use setConfiguration and pass only the annotationConfiguration? As I will never have an web.xml anywhere in that app. And i thought it would be better to use actual class references in the code than strings containing the FQDNs.

What's the difference between:
```
webAppContext.setConfigurations(new Configuration[] {new AnnotationConfiguration(), new JettyWebXmlConfiguration()});
```
and 

```
Configuration.ClassList classlist = Configuration.ClassList.setServerDefault(server);
classlist.addBefore("org.eclipse.jetty.webapp.JettyWebXmlConfiguration",
  "org.eclipse.jetty.annotations.AnnotationConfiguration");
```

The classes implementing the WebApplicationInitializer interface may not be contained in the same jar as the code that starts the server. But I don't now in which jar they would be so what should i specify in setExtraClasses? I cant' use "target/classes" because that's only available when running unpackaged.

**Comment by thuri** [comment]
So I found https://www.eclipse.org/jetty/documentation/current/configuring-webapps.html now ... I can see why it's not enough to use the setConfiguration.

**Comment by janbartel** [comment]
@thuri as per the doco, we don't scan anything from the container classpath, unless it matches a pattern given to the  org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern attribute.  When running jetty from the distro or  from the maven plugin, we set it some sensible defaults, but you will need to set it to include a pattern that matches the jar name, or a pattern that matches a classpath to scan for the spring SCI that calls your WebAppInitializer. This issue from the time when we added the ability for the pattern to point to a classpath (in addition to jars) has more info:   https://bugs.eclipse.org/bugs/show_bug.cgi?id=404176#c5

Also, you can take a look at an embedded example, where we set up to serve one of the standard jetty test wars here: https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/examples/embedded/src/main/java/org/eclipse/jetty/embedded/ServerWithAnnotations.java.  It also sets up some jndi stuff, but you can just ignore that.

**Comment by thuri** [comment]
Hi @janbartel  and thanks for your effort to help me! That's very much appreciated!

As it happens I just got it working with exactly that ContainerIncludeJarPattern thingy when you wrote that comment. I'll see how I do that in the final application. Probably I will pass in a config value.

Again: Thank you very much!

**Comment by joakime** [comment]
> Why can't I use setConfiguration and pass only the annotationConfiguration?

When you call `setConfigurations()` you destroy the default list that's already there.
And you cannot just willy-nilly add `AnnotationConfiguration` where you want to, it needs to be in the correct place.
The order of `Configurations` is important. (we've fixed this nuance in Jetty 10, as it will order Configurations on its own).

**Comment by geekbeast** [comment]
I just upgraded to Jetty 10 and the org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern is working as expected. I've been happily using the AnnotationConfiguration hack since 2014 (https://bugs.eclipse.org/bugs/show_bug.cgi?id=404176#c15) and when I went to upgrade our project for Jetty 10, I added the ContainerIncludeJarPattern line back and it worked like a charm (Still no luck on Jetty 9 and Servlet 3.1). So glad this is finally working and I can delete the hack (I had sub-classed AnnotationConfiguration to allow static initializers to manually register themselves when the class got loaded and then swapped  it with the existing AnnotationConfiguration).

**Comment by geekbeast** [comment]
Also thanks for all the hard work on Jetty :)

**Comment by geekbeast** [comment]
@janbartel I spoke too soon! Went to deploy code that was working fine in IntelliJ and the WebApplicationInitializers did not get picked up again. This time though I was able to track down the issue. We use the gradle application plugin to bundle our dependencies and due to a command line length limitation on windows we set that classpath via a manifest file in the main jar. It turns out that adding the jar that contains the WebApplicationInitializer to the classpath on the command line allows everything to work fine (which is why it worked in IDE). 

I feel like this might be a bug in how jetty gets the classpath, but the work around is below in case anybody comes across the same issue.
```
jar {
    doFirst {
        manifest {
            attributes(
                    "Class-Path": configurations.runtimeClasspath.files.collect { it.getName() }.join(" "),
                    "Main-Class": mainClassName
            )
        }
    }
}

startScripts {
    classpath = files(jar.archiveFile.get().asFile) + classpath.filter { it.getName().startsWith("<YOUR BASE JAR NAME HERE>") }
}

**Comment by joakime** [comment]
That gradle jar / manifest config is for the Server itself (in other words, what class is started by the JVM), and would have no impact on a WebAppContext and it's own isolated WebAppClassloader.

**Comment by geekbeast** [comment]
So I am guessing the class loader for the manifest file is separate from WebAppContext class loader and the reason that the workaround works is that the WebAppContext class loader delegates to System class loader which handles class path variables.

In which case, it seems like the key part is to make sure any initializers are registered with the System class loader if you are using embedded jetty in our particular fashion. 


If this is the case, then it all makes a lot of sense 😄

**Comment by joakime** [comment]
WebAppContext does not delegate to system classloader in the way you expect.

The Servlet Spec specifically calls out the classloader to be the opposite of the Java standard Classloader behavior with regards to parent classloader behavior.
This is all under the umbrella of WebApp Classloader Isolation (which Jetty implements).

This can often cause problems on platforms like OSGi and JPMS.

**Comment by geekbeast** [comment]
I see, somehow adding it to classpath is causing the WebAppContext to pick it up, but even after reading the WebAppClassloader docs I'm not entirely sure how. 

Also want to not that I have two initializers and one wasn't getting picked up either because it is empty (and some how getting omitted) or because whatever mechanism is used to detect WebApplicationInitializers doesn't pick up implementations of an Abstract class that implements the interface. Example: https://github.com/geekbeast/rhizome/commit/63274a74051f67c3394cafa773d74a3b0a633ce1
https://github.com/geekbeast/rhizome/commit/6fa03c36632a87979ea37c980f61ecf4f5717c90

**Comment by janbartel** [comment]
Jetty isn't responsible for instantiating and calling your `WebApplicationIntializers`, that is a Spring concept. Spring has an implementation of `ServletContainerInitializer` that we _are_ responsible for finding, and then that in turn looks for the `WebApplicationInitializers`.  See https://docs.spring.io/spring-security/site/docs/4.2.4.RELEASE/apidocs/org/springframework/security/web/context/AbstractSecurityWebApplicationInitializer.html and https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/WebApplicationInitializer.html.  Perhaps your "empty" Spring initializer is not being called because it cannot be constructed - you have a protected constructor.

**Comment by geekbeast** [comment]
Thanks Jan! I am little confused because based on the comments in `SpringServletContainerInitializer` it declares `@HandleTypes` for `WebApplicationInitializer` and the container (i.e Jetty) was responsible for class path scanning and passing them in as an argument. I was able to use the `ContainerIncludeJarPattern` in combination with adding my jars to the classpath (i.e -cp jvm arg) to get it fully working in the IDE and partially with the Gradle distribution. 

Looking at the code for the `SpringServletContainerInitializer` it has some additional checks to ensure that the passed in class is neither an interface nor abstract, and WebApplicationInitializer is assignable from said passed in class. My initial guess here was that an empty extension of an AbstractClass is failing one of these checks (or its constructor is not accessible, which would be odd since my workaround doesn't address that). A cursory read of ClassInheritanceHandler and ClassInfo processing for where something might get filtered out didn't reveal any obvious candidates. 

Anyway, things are mostly working as expected. Thank you all for the helping me get to the bottom of it-- if I have time I will try to revert the change and attach a debugger at startup to see if class is passed in is rejected or missing. If it is missing maybe something is going wrong with visitor for class processing, but that would be getting really deep in the weeds.
